-- Growth operator foundation: privacy-conscious funnel events, commercial stages,
-- automation audit history, and a human-approved prospect queue.

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  event_name text not null check (
    event_name in (
      'page_view',
      'cta_click',
      'form_start',
      'snapshot_intake_success',
      'snapshot_intake_fail',
      'contact_submit_success',
      'contact_submit_fail',
      'portal_upgrade_click',
      'newsletter_submit_success',
      'newsletter_submit_fail'
    )
  ),
  path text not null check (length(path) between 1 and 300),
  session_id uuid not null,
  properties jsonb not null default '{}'::jsonb
    check (
      jsonb_typeof(properties) = 'object'
      and octet_length(properties::text) <= 4096
    )
);

create index if not exists site_events_occurred_at_idx
  on public.site_events (occurred_at desc);
create index if not exists site_events_event_time_idx
  on public.site_events (event_name, occurred_at desc);
create index if not exists site_events_session_time_idx
  on public.site_events (session_id, occurred_at desc);

comment on table public.site_events is
  'First-party, pseudonymous website funnel events. Never store names, email addresses, free text, full URLs, or IP addresses in properties.';

alter table public.site_events enable row level security;

drop policy if exists "site_events_public_insert" on public.site_events;
create policy "site_events_public_insert"
  on public.site_events for insert
  to anon, authenticated
  with check (
    path like '/%'
    and jsonb_typeof(properties) = 'object'
    and octet_length(properties::text) <= 4096
  );

drop policy if exists "site_events_super_admin_select" on public.site_events;
create policy "site_events_super_admin_select"
  on public.site_events for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid() and p.is_super_admin = true
    )
  );

create table if not exists public.sales_opportunities (
  id uuid primary key default gen_random_uuid(),
  lead_intake_id uuid unique references public.lead_intake_submissions (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  stage text not null default 'new' check (
    stage in (
      'new',
      'qualified',
      'meeting',
      'proposal',
      'won',
      'lost',
      'nurture'
    )
  ),
  plan_key text check (
    plan_key is null or plan_key in (
      'free_snapshot',
      'signal_monitor',
      'signal_growth',
      'signal_elevate',
      'general'
    )
  ),
  monthly_value_cents integer not null default 0 check (monthly_value_cents >= 0),
  is_test boolean not null default false,
  next_action_at timestamptz,
  won_at timestamptz,
  lost_at timestamptz,
  notes text
);

create index if not exists sales_opportunities_stage_idx
  on public.sales_opportunities (stage, is_test, updated_at desc);
create index if not exists sales_opportunities_next_action_idx
  on public.sales_opportunities (next_action_at)
  where next_action_at is not null and stage not in ('won', 'lost');

comment on table public.sales_opportunities is
  'Commercial funnel. A processed snapshot is not revenue; only stage=won contributes to customer/MRR reporting.';

alter table public.sales_opportunities enable row level security;

drop policy if exists "sales_opportunities_super_admin_all" on public.sales_opportunities;
create policy "sales_opportunities_super_admin_all"
  on public.sales_opportunities for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_super_admin = true
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_super_admin = true
    )
  );

create or replace function public.touch_sales_opportunity_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  if new.stage = 'won' and new.won_at is null then
    new.won_at := now();
  end if;
  if new.stage = 'lost' and new.lost_at is null then
    new.lost_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists sales_opportunities_touch_updated_at on public.sales_opportunities;
create trigger sales_opportunities_touch_updated_at
before update on public.sales_opportunities
for each row execute function public.touch_sales_opportunity_updated_at();

create or replace function public.create_sales_opportunity_from_intake()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  estimated_monthly_value integer;
begin
  estimated_monthly_value := case new.inquiry_plan
    when 'signal_monitor' then 14900
    when 'signal_growth' then 49900
    when 'signal_elevate' then 99900
    else 0
  end;

  insert into public.sales_opportunities (
    lead_intake_id,
    stage,
    plan_key,
    monthly_value_cents,
    is_test,
    next_action_at
  )
  values (
    new.id,
    'new',
    new.inquiry_plan,
    estimated_monthly_value,
    false,
    now() + interval '1 day'
  )
  on conflict (lead_intake_id) do nothing;

  return new;
end;
$$;

drop trigger if exists lead_intake_create_sales_opportunity
  on public.lead_intake_submissions;
create trigger lead_intake_create_sales_opportunity
after insert on public.lead_intake_submissions
for each row execute function public.create_sales_opportunity_from_intake();

revoke all on function public.create_sales_opportunity_from_intake()
  from public, anon, authenticated, service_role;

-- The owner confirmed there have not yet been real leads. Preserve historical
-- intake data while excluding it from commercial reporting.
insert into public.sales_opportunities (
  lead_intake_id,
  stage,
  plan_key,
  monthly_value_cents,
  is_test
)
select
  li.id,
  'new',
  li.inquiry_plan,
  case li.inquiry_plan
    when 'signal_monitor' then 14900
    when 'signal_growth' then 49900
    when 'signal_elevate' then 99900
    else 0
  end,
  true
from public.lead_intake_submissions li
on conflict (lead_intake_id) do update set is_test = true;

create table if not exists public.automation_runs (
  id uuid primary key default gen_random_uuid(),
  run_kind text not null check (
    run_kind in ('daily_report', 'codex_operator', 'prospect_research')
  ),
  status text not null check (
    status in ('started', 'succeeded', 'failed', 'skipped', 'approval_required')
  ),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  summary text,
  metrics jsonb not null default '{}'::jsonb,
  artifact_path text,
  error_message text
);

create index if not exists automation_runs_kind_time_idx
  on public.automation_runs (run_kind, started_at desc);

alter table public.automation_runs enable row level security;

drop policy if exists "automation_runs_super_admin_select" on public.automation_runs;
create policy "automation_runs_super_admin_select"
  on public.automation_runs for select
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_super_admin = true
    )
  );

create table if not exists public.prospect_queue (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  business_name text not null,
  website_url text,
  source_url text,
  city text not null default 'Cincinnati',
  state text not null default 'OH',
  fit_score integer not null default 0 check (fit_score between 0 and 100),
  status text not null default 'researched' check (
    status in (
      'researched',
      'approval_required',
      'approved',
      'contacted',
      'replied',
      'dismissed'
    )
  ),
  rationale text,
  public_signals jsonb not null default '{}'::jsonb,
  draft_subject text,
  draft_body text,
  approved_at timestamptz,
  contacted_at timestamptz,
  unique (business_name, city, state)
);

create index if not exists prospect_queue_status_score_idx
  on public.prospect_queue (status, fit_score desc, updated_at desc);

comment on table public.prospect_queue is
  'Public-business research and draft outreach. Sending remains human-approved; no personal contact enrichment is stored.';

alter table public.prospect_queue enable row level security;

drop policy if exists "prospect_queue_super_admin_all" on public.prospect_queue;
create policy "prospect_queue_super_admin_all"
  on public.prospect_queue for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_super_admin = true
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_super_admin = true
    )
  );

create or replace function public.growth_operator_metrics(p_days integer default 7)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with bounds as (
    select
      now() - make_interval(days => greatest(1, least(coalesce(p_days, 7), 90))) as period_start,
      now() - interval '1 day' as day_start
  ),
  event_totals as (
    select
      count(*) filter (where occurred_at >= (select day_start from bounds))::int as events_24h,
      count(*)::int as events_period,
      count(distinct session_id) filter (
        where occurred_at >= (select day_start from bounds)
      )::int as sessions_24h,
      count(distinct session_id)::int as sessions_period,
      count(*) filter (where event_name = 'page_view')::int as page_views,
      count(*) filter (where event_name = 'cta_click')::int as cta_clicks,
      count(*) filter (where event_name = 'form_start')::int as form_starts,
      count(*) filter (
        where event_name in ('snapshot_intake_success', 'contact_submit_success')
      )::int as form_completions,
      count(*) filter (where event_name = 'portal_upgrade_click')::int as portal_upgrade_clicks
    from public.site_events
    where occurred_at >= (select period_start from bounds)
  ),
  sales as (
    select
      count(*) filter (where stage = 'new')::int as new_count,
      count(*) filter (where stage = 'qualified')::int as qualified_count,
      count(*) filter (where stage = 'meeting')::int as meeting_count,
      count(*) filter (where stage = 'proposal')::int as proposal_count,
      count(*) filter (where stage = 'won')::int as won_count,
      count(*) filter (where stage = 'lost')::int as lost_count,
      coalesce(sum(monthly_value_cents) filter (where stage = 'won'), 0)::int as mrr_cents,
      count(*) filter (
        where next_action_at <= now() and stage not in ('won', 'lost')
      )::int as follow_ups_due
    from public.sales_opportunities
    where is_test = false
  ),
  intake as (
    select
      count(*) filter (where processing_status = 'pending')::int as pending,
      count(*) filter (where processing_status = 'processing')::int as processing,
      count(*) filter (where processing_status = 'failed')::int as failed,
      count(*) filter (
        where created_at >= (select period_start from bounds)
      )::int as submissions_period
    from public.lead_intake_submissions li
    where not exists (
      select 1
      from public.sales_opportunities so
      where so.lead_intake_id = li.id and so.is_test = true
    )
  ),
  prospects as (
    select
      count(*) filter (where status = 'approval_required')::int as approval_required,
      count(*) filter (where status = 'approved')::int as approved,
      count(*) filter (where status = 'contacted')::int as contacted,
      count(*) filter (where status = 'replied')::int as replied
    from public.prospect_queue
  )
  select jsonb_build_object(
    'generated_at', now(),
    'days', greatest(1, least(coalesce(p_days, 7), 90)),
    'events', to_jsonb(event_totals),
    'sales', to_jsonb(sales),
    'intake', to_jsonb(intake),
    'prospects', to_jsonb(prospects)
  )
  from event_totals, sales, intake, prospects;
$$;

revoke all on function public.growth_operator_metrics(integer)
  from public, anon, authenticated;
grant execute on function public.growth_operator_metrics(integer) to service_role;
