alter table public.prospect_queue
  add column if not exists scheduled_for timestamptz,
  add column if not exists first_opened_at timestamptz,
  add column if not exists last_opened_at timestamptz,
  add column if not exists open_count integer not null default 0,
  add column if not exists first_clicked_at timestamptz,
  add column if not exists last_clicked_at timestamptz,
  add column if not exists click_count integer not null default 0,
  add column if not exists last_clicked_url text;

alter table public.prospect_queue
  drop constraint if exists prospect_queue_send_status_check;
alter table public.prospect_queue
  add constraint prospect_queue_send_status_check check (
    send_status in (
      'not_ready',
      'pending',
      'sending',
      'scheduled',
      'sent',
      'failed',
      'bounced',
      'complained'
    )
  );

create table if not exists public.prospect_email_events (
  id bigint generated by default as identity primary key,
  resend_event_id text not null unique,
  prospect_id uuid not null references public.prospect_queue(id) on delete cascade,
  event_type text not null,
  occurred_at timestamptz not null,
  link_url text,
  created_at timestamptz not null default now()
);

alter table public.prospect_email_events enable row level security;
revoke all on table public.prospect_email_events from public, anon, authenticated;

create or replace function public.record_prospect_email_event(
  p_resend_event_id text,
  p_email_id text,
  p_event_type text,
  p_occurred_at timestamptz,
  p_link_url text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id uuid;
begin
  select id into target_id
  from public.prospect_queue
  where sent_message_id = p_email_id
  limit 1;

  if target_id is null then
    return false;
  end if;

  insert into public.prospect_email_events (
    resend_event_id,
    prospect_id,
    event_type,
    occurred_at,
    link_url
  )
  values (
    p_resend_event_id,
    target_id,
    p_event_type,
    p_occurred_at,
    left(p_link_url, 1000)
  )
  on conflict (resend_event_id) do nothing;

  if not found then
    return true;
  end if;

  update public.prospect_queue
  set
    status = case
      when p_event_type in ('email.sent', 'email.delivered') then 'contacted'
      else status
    end,
    contacted_at = case
      when p_event_type in ('email.sent', 'email.delivered') then coalesce(contacted_at, p_occurred_at)
      else contacted_at
    end,
    send_status = case
      when p_event_type in ('email.sent', 'email.delivered') then 'sent'
      when p_event_type = 'email.bounced' then 'bounced'
      when p_event_type = 'email.complained' then 'complained'
      else send_status
    end,
    first_opened_at = case
      when p_event_type = 'email.opened' then coalesce(first_opened_at, p_occurred_at)
      else first_opened_at
    end,
    last_opened_at = case
      when p_event_type = 'email.opened' then p_occurred_at
      else last_opened_at
    end,
    open_count = open_count + case when p_event_type = 'email.opened' then 1 else 0 end,
    first_clicked_at = case
      when p_event_type = 'email.clicked' then coalesce(first_clicked_at, p_occurred_at)
      else first_clicked_at
    end,
    last_clicked_at = case
      when p_event_type = 'email.clicked' then p_occurred_at
      else last_clicked_at
    end,
    click_count = click_count + case when p_event_type = 'email.clicked' then 1 else 0 end,
    last_clicked_url = case
      when p_event_type = 'email.clicked' then left(p_link_url, 1000)
      else last_clicked_url
    end,
    updated_at = now()
  where id = target_id;

  return true;
end;
$$;

revoke all on function public.record_prospect_email_event(
  text, text, text, timestamptz, text
) from public, anon, authenticated;
grant execute on function public.record_prospect_email_event(
  text, text, text, timestamptz, text
) to service_role;
